# =================================================================================================
# DOCUMENTATION STATEMENT: lab_specific_code/specs.py
# -------------------------------------------------------------------------------------------------
# Source:    Claude Code (Anthropic's CLI coding assistant), model Claude Opus 5.5 (claude-opus-5-5)
# Date:      2026-10-07, single extended session
# AI level:  AI Level III. GenAI was used as a feedback tool on student-generated code. All code in
#            this file is my own. Claude reviewed it and described problems and possible fixes in
#            words, and I made every change myself. The only AI-written code in the project is the
#            PDF report generator (claude/claudes_code/reports.py), a quality-of-life tool rather
#            than a substantive part of the project.
# Permission: My instructor permitted this level of AI through verbal conversation in
#            class earlier in the semester.
#
# Help received for this file (what Claude provided -> where -> what I changed -> result):
#
#  1. Resistor list. Claude noticed that 92 / 920 / 9.2k / 92k / 920k aren't E24 values (a typo
#     for 82). -> I corrected them to 82 / 820 / 8.2k / 82k / 820k. -> Only real standard values
#     can be chosen.
#  2. Capacitor units. Claude pointed out that CAPACITORS was in uF while C_MIN / C_MAX were in
#     farads. -> I converted CAPACITORS to farads. -> Units are consistent.
#  3. Hardcoded load. Claude suggested keeping RL with the other specs. -> I added CS_RL here.
#  4. Monte Carlo deviations. After I added Monte Carlo variation, Claude noted that a 5 % standard
#     deviation was too wide for 5 %-tolerance resistors (about a third of samples would fall
#     outside tolerance), and that transistor parameters vary more than resistors. -> I split the
#     deviation into COMP_DEV_PERC_STDEV (2 %, passive parts) and TRANS_DEV_PERC_STDEV (5 %, Kn and
#     Vt). -> Resistor variation is now realistic, and transistor variation is modeled separately.
#  5. Swing margin. Claude noted that a 0.1 V margin was too thin to cover effects left out of the
#     swing estimate and differences between the model and the bench. -> I raised CS_MARGIN to
#     0.75 V.
#  6. Target constants. Claude identified that the negative Av target caused a sign error in
#     scoring. -> I removed the CS_TARGET_* constants when I rewrote score_range (see util.py).
#
# This documentation statement was generated by Claude (Claude Opus 5.5 via Claude Code) at the
# student's request, from the session record. The student should verify it, and the full
# conversation transcript is to be provided to the instructor.
# =================================================================================================

import random



USE_MONTE_CARLO = True
COMP_DEV_PERC_STDEV = 2 / 100
TRANS_DEV_PERC_STDEV = 5 / 100
MONTE_CARLO_REPS = 100




# SPECS

VDD_MIN = 10
VDD_MAX = 20
C_MIN = 0.00001
C_MAX = 0.0001
RESISTOR_RATING = 0.25
MAX_RESISTORS = 2



# VALUES

RESISTORS = [1, 10, 27, 33, 47, 51, 56, 68, 82, 91, 1000000, 2000000, 5100000, 6800000, 10000000, 100, 1000, 10000, 100000, 110, 1100, 11000, 110000, 120, 1200, 12000, 120000, 130, 1300, 13000, 130000, 150, 1500, 15000, 150000, 160, 1600, 16000, 160000, 180, 1800, 18000, 180000, 200, 2000, 20000, 200000, 220, 2200, 22000, 220000, 240, 2400, 24000, 240000, 270, 2700, 27000, 270000, 300, 3000, 30000, 300000, 330, 3300, 33000, 330000, 360, 3600, 36000, 360000, 390, 3900, 39000, 390000, 430, 4300, 43000, 430000, 470, 4700, 47000, 470000, 510, 5100, 51000, 510000, 560, 5600, 56000, 560000, 620, 6200, 62000, 620000, 680, 6800, 68000, 680000, 750, 7500, 75000, 750000, 820, 8200, 82000, 820000, 910, 9100, 91000, 910000]
CAPACITORS = [0.000010, 0.000022, 0.000033, 0.000047, 0.000100]
# Kn = 0.08
# Vt = 2
# VA = 100
# R_FG = 50


def Kn(exact=False):
    val = 0.08
    if (not USE_MONTE_CARLO) or exact:
        return val
    return val + (random.gauss(0, TRANS_DEV_PERC_STDEV) * val)

def Vt(exact=False):
    val = 2
    if (not USE_MONTE_CARLO) or exact:
        return val
    return val + (random.gauss(0, TRANS_DEV_PERC_STDEV) * val)

def VA(exact=False):
    val = 100
    if (not USE_MONTE_CARLO) or exact:
        return val
    return val + (random.gauss(0, COMP_DEV_PERC_STDEV) * val)

def R_FG(exact=False):
    val = 50
    if (not USE_MONTE_CARLO) or exact:
        return val
    return val + (random.gauss(0, COMP_DEV_PERC_STDEV) * val)




####################### CS_AMP #######################

# SPECS
CS_MAX_ID = 0.005
CS_MIN_RI = 100000
CS_MAX_RI = 150000
CS_RO_MAX = 5100
CS_MIN_AV = -30
CS_MAX_AV = -15
CS_MARGIN = 0.75




# VALUES

# CS_RL = 100000

def CS_RL(exact=False):
    val = 100000
    if (not USE_MONTE_CARLO) or exact:
        return val
    return val + (random.gauss(0, COMP_DEV_PERC_STDEV) * val)







