# =================================================================================================
# DOCUMENTATION STATEMENT: lab_specific_code/util.py
# -------------------------------------------------------------------------------------------------
# Source:    Claude Code (Anthropic's CLI coding assistant), model Claude Opus 5.5 (claude-opus-5-5)
# Date:      2026-10-07, single extended session
# AI level:  AI Level III. GenAI was used as a feedback tool on student-generated code. All code in
#            this file is my own. Claude reviewed it and described problems and possible fixes in
#            words and formulas, and I made every change myself. The only AI-written code in the
#            project is the PDF report generator (claude/claudes_code/reports.py), a
#            quality-of-life tool rather than a substantive part of the project.
# Permission: My instructor permitted this level of AI through verbal conversation in
#            class earlier in the semester.
#
# Help received for this file (what Claude provided -> where -> what I changed -> result):
#
#  1. Resistor.check_power. Claude reviewed the single, series and parallel worst-case power logic
#     and confirmed it was correct. -> No change needed.
#  2. score_range redesign. Claude identified that my first version returned the same score
#     anywhere inside the range, so the optimizer had no reason to stay away from spec limits.
#     For my next version (margin divided by the target), Claude identified four problems:
#     (a) a negative target (Av) flipped the margin bonus and pinned Av at the limit, (b) the bonus
#     had no upper bound, so one term could exceed 1, (c) one-sided specs got a fake lower limit of
#     0, and (d) the bonus was scaled unevenly between specs. Claude suggested normalizing the
#     margin by half the range width, capping it, and treating one-sided specs separately.
#     -> I rewrote score_range to use margin / (half the range width), and wrote score_over and
#     score_under for one-sided limits, with a capped bonus and normalized penalties.
#     -> Specs are scored with consistent margins, Av centres inside its range, and lower power is
#     no longer penalized.
#  3. Out-of-range penalties in raw units. Claude pointed out that the penalty depended on each
#     quantity's units (missing Ri by 1 kOhm scored -999, while missing ID by 1 mA barely
#     registered). -> I normalized the below-range penalty in score_range and the penalty in
#     score_over.
#  4. Dedupe loop in gen_all_resistors. Claude identified that the loop skipped a comparison after
#     each removal. -> I step the index back after a removal.
#  5. Monte Carlo noise in Resistor.eval. Claude identified that adding random deviation inside
#     eval() also made gen_all_resistors sort and dedupe on noisy values, which scrambled about half
#     the neighbouring entries in the list. -> I added an 'exact' flag to eval() and use exact
#     values for sorting and deduping. -> The resistor list is ordered by nominal value again, so
#     mutation steps move to neighbouring values as intended.
#
# This documentation statement was generated by Claude (Claude Opus 5.5 via Claude Code) at the
# student's request, from the session record. The student should verify it, and the full
# conversation transcript is to be provided to the instructor.
# =================================================================================================

import lab_specific_code.specs as spec
import random


ALLRES = []

def parallel(resistors):
    tot = 0
    for r in resistors:
        tot += (r ** -1)
    return (tot ** -1)

def series(resistors):
    tot = 0
    for r in resistors:
        tot += r
    return tot


class Resistor:
    def __init__(self):
        self.resistors = []
        self.in_parallel = False

    def eval(self, exact=False):
        out = 0
        if not self.is_valid():
            print("INVALID RESISTOR")
            exit(-1)
        if self.in_parallel:
            out = parallel(self.resistors)
        else:
            out = series(self.resistors)

        if (not spec.USE_MONTE_CARLO) or exact:
            return out

        return out + (random.gauss(0, spec.COMP_DEV_PERC_STDEV) * out)

    def is_valid(self):
        if not len(self.resistors):
            return False

        if len(self.resistors) > spec.MAX_RESISTORS:
            return False

        return True

    # based on a given voltage across, find the highest power lost over any of the individual resistors
    def check_power(self, voltage):
        if len(self.resistors) == 1: # single
            return (voltage ** 2) / self.eval()

        if (self.in_parallel): # parallel
            r = min(self.resistors)
            return (voltage ** 2) / r

        # series
        i = voltage / self.eval()
        r = max(self.resistors)
        return (i ** 2) * r





def gen_all_resistors():
    global ALLRES

    if len(ALLRES):
        return ALLRES

    if spec.MAX_RESISTORS != 2:
        print("ERROR: gen all resistors not defined for MAX_RESISTORS != 2")
        exit(-1)

    res = []

    for r in spec.RESISTORS:
        cr = Resistor()
        cr.resistors = [r]
        res.append(cr)

    for i in range(len(spec.RESISTORS)):
        for j in range(i, len(spec.RESISTORS)):
            cr1 = Resistor()
            cr1.resistors = [spec.RESISTORS[i], spec.RESISTORS[j]]
            res.append(cr1)

            cr2 = Resistor()
            cr2.resistors = [spec.RESISTORS[i], spec.RESISTORS[j]]
            cr2.in_parallel = True
            res.append(cr2)


    res.sort(key= lambda r : r.eval(True)) # deduplicate the resistors
    index = 0
    while (index < len(res) - 1):
        index += 1
        if (abs(res[index].eval(True) - res[index - 1].eval(True)) < 0.1): # remove very similar resistors
            if len(res[index].resistors) > len(res[index - 1].resistors):
                res.remove(res[index])
            else:
                res.remove(res[index - 1])
            index -= 1
    
    ALLRES = res
    return res





def score_range(val, min_val, max_val):
    if (val < max_val) and (val > min_val):
        margin = min(val - min_val, max_val - val) / ((max_val - min_val) / 2)
        return 0.9 + 0.1 * margin

    if (val < min_val):
        return 0.9 - (min_val - val) / (max_val - min_val)
    return 0.9 - (val - max_val)

def score_over(val, min_val):
    if (val < min_val):
        return 0.9 - ((min_val - val) / abs(min_val))

    return 0.9 + 0.1 * min(((val - min_val) / abs(min_val)), 1)

def score_under(val, max_val):
    return score_over(-val, -max_val)

def score_lerp(val, max, invert=False):
    out = (val / max)
    if invert:
        return 1 - out
    return out

