# =================================================================================================
# DOCUMENTATION STATEMENT: main.py (and project overview)
# -------------------------------------------------------------------------------------------------
# Source:    Claude Code (Anthropic's CLI coding assistant), model Claude Opus 5.5 (claude-opus-5-5)
# Date:      2026-10-07, single extended session
# AI level:  AI Level III. GenAI was used as a feedback tool on student-generated code. All of the
#            code in this project is my own, with one exception: the PDF report generator described
#            below, a quality-of-life improvement rather than a substantive part of the project.
#            For my code, Claude reviewed what I wrote and described problems and possible fixes in
#            words and formulas, and I made every change myself. Claude wrote no circuit analysis,
#            scoring or optimization code. Each of my code files has its own documentation
#            statement listing the help it received.
# Permission: My instructor permitted this level of AI through verbal conversation in
#            class earlier in the semester.
#
# REPORT GENERATOR (claude/claudes_code/reports.py, imported above, called as renderCSAmpReport)
#   - Written entirely by Claude at my request, and revised as my code changed. It is the only
#     AI-written code in the project.
#   - Purpose: produce a one-page PDF (cs_amp_design.pdf) summarizing the optimized CS stage.
#     The top of the page is a schematic of the Day 1 circuit (drawn with the reportlab library),
#     labeled with each resistor's parts and value, VDD, the capacitors, the load, and the DC
#     node voltages and drain current. The bottom has a table of analyzed values and the score
#     breakdown.
#   - How it works: it performs NO circuit analysis or scoring of its own. Every number comes from
#     calling my functions: the Circuit_Sol getters, analyzeCSAmpModel, CSAmpModelScoreBreakdown
#     and scoreCSAmpModel. Nominal values are produced by temporarily setting
#     spec.USE_MONTE_CARLO to False while calling my functions. When Monte Carlo is enabled, it
#     also calls my functions repeatedly with variation on (200 analysis/breakdown calls and 20
#     scoreCSAmpModel calls) and reports only bookkeeping on what they return: the min and max of
#     each analyzed value, the fraction of calls where "Meets req" passed, and the mean, min and
#     max score. The rest is formatting (SI prefixes, tables, colors).
#
# Help received for this file (what Claude provided -> where -> what I changed -> result):
#
#  1. Annealing settings. Claude identified that max_learn_rate = 1 made the first ~20 epochs
#     effectively random (mutation steps of thousands of list positions), and that a high anneal
#     rate (0.75) froze the search by about epoch 13, leaving one seed stuck on a design that
#     failed the gain spec. -> I set anneal_rate = 0.1 and max_learn_rate = 0.2. -> Training
#     refines steadily, and runs with different seeds reach consistent results.
#  2. Reproducibility. Claude suggested seeding the random generator so a design can be
#     regenerated. -> I added random.seed(42). -> Runs are reproducible.
#  3. Overall review process. Over several rounds, Claude evaluated the training methodology and
#     scoring, ran my code with several seeds to show the effect of each issue, and wrote an HTML
#     code review (claude/claude_transcripts/Code_Review1.html) and "TODO" feedback comments. I
#     made all of the resulting code changes myself (see each file's statement).
#
# Overall result: the optimizer produces a CS-stage design that meets every modeled
# specification, with margin, and passes all modeled requirements across Monte Carlo component
# variation.
#
# This documentation statement was generated by Claude (Claude Opus 5.5 via Claude Code) at the
# student's request, from the session record. The student should verify it, and the full
# conversation transcript is to be provided to the instructor.
# =================================================================================================

import random
from lab_specific_code.CS_Amp import *
from libs.optimizer import *
from claude.claudes_code.reports import *


random.seed(42)
optimizer = EvolutionaryOptimizer(createCSAmpModel())

optimizer.max_learn_rate = 0.2
optimizer.anneal_rate = 0.1
optimizer.generation_size = 1000
cs_amp = optimizer.train(scoreCSAmpModel, 50, 10, True)

renderCSAmpReport(cs_amp, "./cs_amp_design.pdf")
