# =================================================================================================
# DOCUMENTATION STATEMENT: libs/optimizer.py
# -------------------------------------------------------------------------------------------------
# Source:    Claude Code (Anthropic's CLI coding assistant), model Claude Opus 5.5 (claude-opus-5-5)
# Date:      2026-10-07, single extended session
# AI level:  AI Level III. GenAI was used as a feedback tool on student-generated code. All code in
#            this file is my own. Claude reviewed it and described problems and possible fixes in
#            words, and I made every change myself. The only AI-written code in the project is the
#            PDF report generator (claude/claudes_code/reports.py), a quality-of-life tool rather
#            than a substantive part of the project.
# Permission: My instructor permitted this level of AI through verbal conversation in
#            class earlier in the semester.
#
# Help received for this file (what Claude provided -> where -> what I changed -> result):
#
#  1. Parent-selection bug in train(). Claude walked through an example showing that when a new
#     candidate beat the best design, the j-loop also overwrote the second slot. Both parents then
#     became the same design, the previous best was lost, and crossover did nothing. Claude also
#     noted that the second slot's score wasn't shifted along with its design. -> I shift the score
#     together with the design and break out of the loop after placing a candidate. -> The two
#     parents now stay distinct, and the best design is never lost.
#  2. Score / solution ordering. Claude noticed that the initial swap reordered 'best' but not
#     'best_scores'. -> I swap both together.
#  3. Redundant scoring. Claude pointed out that the first two candidates were scored twice per
#     epoch. -> I reuse the scores already computed. -> Fewer evaluations, which matters more now
#     that each score runs Monte Carlo repetitions.
#  4. Annealing schedule. Claude explained that with the linear schedule, the mutation step (as a
#     fraction of the ~11,000-entry resistor list) was so large that most of training was
#     effectively random search, and that exp_fudge_factor ignored max_learn_rate. -> I made the
#     exponential schedule the default and scaled it by max_learn_rate. Tuning values are in
#     main.py. -> Training moves gradually from exploring to fine-tuning, and different seeds reach
#     consistent results.
#
# This documentation statement was generated by Claude (Claude Opus 5.5 via Claude Code) at the
# student's request, from the session record. The student should verify it, and the full
# conversation transcript is to be provided to the instructor.
# =================================================================================================

import math


class OptimizeableSolution:
    def __init__(self):
        print("Cannot initialize abstract class.")
        
    def getRandomSolution(self):
        print("Function not implemented")
    
    def fudgeSelf(self, fudge_factor):
        print("Function not implemented")
    
    # create a new solution that is the old sulution randomly fudged a bit
    def fudgeSolution(self, fudge_factor):
        print("Function not implemented")
    
    # create new solutions based on two parents
    def makeBabies(self, other_parent, fudge_factor, count, include_parents=True):
        print("Function not implemented")
    


class EvolutionaryOptimizer:
    def __init__(self, seed_sol : OptimizeableSolution):
        self.seed = seed_sol
        self.max_learn_rate = 1
        self.generation_size = 100
        self.fudge_factor_calc = self.exp_fudge_factor
        self.anneal_rate = 0.5
    
    def lerp_fudge_factor(self, cur_epoch, last_epoch):
        perc = (last_epoch - cur_epoch) / last_epoch
        return perc * self.max_learn_rate
    
    def exp_fudge_factor(self, cur_epoch, last_epoch):
        return math.exp(-self.anneal_rate * (cur_epoch)) * self.max_learn_rate
    
    def train(self, score, epochs, print_interval=10, random_first_gen=True):
        print("Beginning training...")

        best_scores = []
        best = []
        if (not random_first_gen):
            best = [self.seed.fudgeSolution(0), self.seed.fudgeSolution(0)] # copy seed solution
        
        generation = []
        for c_ep in range(epochs):
            if ((c_ep == 0) and random_first_gen):
                for i in range(self.generation_size):
                    generation.append(self.seed.fudgeSolution(0).getRandomSolution())
            else:
                generation = best[0].makeBabies(best[1], self.fudge_factor_calc(c_ep, epochs), 
                                                self.generation_size, True)
            best = [generation[0], generation[1]]
            best_scores = [score(generation[0]), score(generation[1])]

            if (best_scores[1] > best_scores[0]): # swap to maintain order
                best[1], best[0] = best[0], best[1]
                best_scores[1], best_scores[0] = best_scores[0], best_scores[1]

            for i in range(2, len(generation)):
                new_score = score(generation[i])
                for j in range(len(best)):
                    if (best_scores[j] < new_score):
                        if (j == 0):
                            best[j + 1] = best[j]
                            best_scores[j + 1] = best_scores[j]
                        best[j] = generation[i]
                        best_scores[j] = new_score
                        break
                
            top_performance = max(best_scores[0], best_scores[1])
            if (c_ep % print_interval == 0):
                print("\tFinished epoch " + str(c_ep) + " out of " + str(epochs) 
                      + " : SCORE (" + str(top_performance) + ")")
        
        print("TRAINING COMPLETE: Best = " + str(max(best_scores[0], best_scores[1])))
        
        if (best_scores[0] > best_scores[1]):
            return best[0]
        return best[1]
            
        
        
        
        
    








